import type { Metadata } from "next";
import IndexLayout from "@/components/Layout";
import "./global.css"


export const metadata: Metadata = {
  title: "Yami-chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <IndexLayout>{children}</IndexLayout>
        </body>
    </html>
  );
}
